console.log("Подивимось результат виразу: 'number' + 3 + 3"); 
var result = "результат:", title="Подивимось результат виразу:";
console.log(result,'number' + 3 + 3);
console.log(title," null + 3");
console.log(result, null + 3);
console.log(title,"5 && \"qwerty\"");
console.log(result, 5 && "qwerty");
console.log(title,"+'40' + +'2' + \"hillel\"");
console.log(result, +'40' + +'2' + "hillel");
console.log( title,"'10' - 5 === 6");
console.log(result, '10' - 5 === 6 );
console.log(title," true + false");
console.log(result, true + false);
console.log(title,"'4px' - 3");
console.log(result, '4px' - 3);
console.log(title,"'4px' - 3");
console.log(result, '4px' - 3);
console.log(title," '6' + 3 ** 0");
console.log(result, '6' + 3 ** 0);
console.log(title, "12 / \'6\'");
console.log(result, 12 / '6');
console.log(title," '10' + (5 === 6)");
console.log(result, '10' + (5 === 6));
console.log(title, " null == ''");
console.log(result, null == '');
console.log(title, " 3 ** (9 / 3)");
console.log(result, 3 ** (9 / 3));
console.log(title, " !!'false' == !!'true'");
console.log(result, !!'false' == !!'true');
console.log(title," 0 || '0' && 1");
console.log(result, 0 || '0' && 1);
console.log(title," (+null == false) < 1");
console.log(result, (+null == false) < 1);
console.log(title," false && (false || true)");
console.log(result, false && (false || true));
console.log(title, " (+null == false) < 1 ** 5");
console.log(result, (+null == false) < 1 ** 5);
